name: Xcode - Build and Analyze

on: workflow_dispatch

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: installDependencies
        run: |
          brew install meson ninja
      - name: Pre-build Meson Core
        run: |
          find . -name "project.pbxproj" -exec sed -i '' 's/app.ish/com.yourcompany/g' {} +
          meson setup builddir --backend=ninja
          ninja -C builddir
      - name: Build
        env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
        run: |
          xcodebuild -list
          echo "A"
          xcodebuild -workspace iSH.xcodeproj/project.xcworkspace -scheme iSH -destination 'generic/platform=iOS' -configuration Release \ CODE_SIGNING_ALLOWED=No \ CODE_SIGNING_REQUIRED=No \ CODE_SIGN_IDENTITY="" \ CODE_SIGNING_STYLE=Manual \-archivePath ".github/build/iSH.xcarchive" -IDEBuildOperationMaxNumberOfConcurrentCompileTasks=1 clean archive  
          echo "B"
    
